using CodeReview.Orchestrator.Analysis.Models;

namespace CodeReview.Orchestrator.Feedback
{
    /// <summary>
    /// Builds a concise global review summary for the Pull Request.
    /// </summary>
    public class ReviewSummaryBuilder
    {
        /// <summary>
        /// Build a textual summary from issues and optional LLM feedback.
        /// </summary>
        public string BuildSummary(IEnumerable<CodeIssue> issues, string? llmResponse)
        {
            var total = issues?.Count() ?? 0;
            var critical = issues?.Count(i => string.Equals(i.Severity, "Critical", StringComparison.OrdinalIgnoreCase)) ?? 0;
            var major = issues?.Count(i => string.Equals(i.Severity, "Major", StringComparison.OrdinalIgnoreCase)) ?? 0;

            var sb = new System.Text.StringBuilder();
            sb.AppendLine($"Automated Code Review Summary\nRun generated by CodeReview.Orchestrator\nTotal issues: {total}");
            sb.AppendLine($"Critical: {critical}, Major: {major}");
            sb.AppendLine();
            sb.AppendLine("LLM Analysis:");
            sb.AppendLine(llmResponse ?? "(LLM disabled or no response)");

            sb.AppendLine();
            sb.AppendLine("Notes: This summary is generated automatically. Integrate GitHub API to post to the Pull Request.");

            return sb.ToString();
        }
    }
}
